- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  become_method: sudo
  tasks:
  - name: Update OS
    package:
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install python3-pip
    package:
      name: ['python3-pip']
  - name: Install virtualenv
    pip:
      name: ['virtualenv']
