- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  become_method: sudo
  tasks:
  - name: Update OS
    package:
      name: '*'
      state: latest
  - name: Install python3-pip
    package:
      name: ['python3-pip']
  - name: Install virtual-env
    pip:
      name: ['virtualenv']
