- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  become: yes
  become_method: sudo
  tasks:
  - name: Update OS
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install python3-pip
    package:
      name: ['python3-pip']
  - name: Install virtualenv and docker 
    pip:
      name: ['virtualenv', 'docker']
  - name: Build flask-api Container 
    docker_image:
      path: /vagrant 
      name: flask-api
      tag: latest
      state: present
  - name: Start flask-api Container
    docker_container:
      name: flask-api
      state: started
      image: flask-api:latest
      detach: yes
      published_ports: 5000:5000
      volumes: 
        - /vagrant/app:/app

